# Locations
TRIBECA = 'TRIBECA'
FLATIRON = 'FLATIRON'
WILLIAMSBURG = 'WILLIAMSBURG'
UPPER_EAST_SIDE = 'UPPER_EAST_SIDE'

LOCATION_CHOICES = (
    (TRIBECA, 'TRIBECA'),
    (FLATIRON, 'FLATIRON'),
    (WILLIAMSBURG, 'WILLIAMSBURG'),
    (UPPER_EAST_SIDE, 'UPPER_EAST_SIDE')
)

# Equipment Provided
YOGA_MAT = 'YOGA_MAT'
BICYCLE = 'BICYCLE'
TOWELS = 'TOWELS'

# Equipment Required
